# -*- coding: utf-8 -*-
"""Synthetic_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UO_jOiFmRha_FCcSpmo7gvZTBWAIf2-m
"""

#Rule based engine(We can't use GAN because that requires real datasets)
#Generative AI require real datasets
#protein abundane levels do not follow uniform distribution because that means every protein abundance value has equal probability of occuring
#protein abundance values cluster around only certain values and not only subset of proteins have a high abundance value rather than most of it and most of them have low-moderate abundance values
#for normal distribution random.normalvariate(mean,stdev)
#Nump=np.random.normal(loc,scale,size)
#Uniform distribution =random.uniform(a,b)
#Numpy=np.random.uniform(loc,size)
#log normal distribution=random.lognormvariate(mean, stdev)
#Numpy= numpy.random.lognormal()
#np.random.gamma()
#protein abundance levels follow a log normal or gamma distribution because biological data tend to be skewed with high low abundance values and high extreme values
#log normal and gamma distributions do not produce values between 0 and 1 and rather need to be further normalised
#tumor classification and grade are independent of age
#poor correlation between RNA levels and protein abundance
#TPM value threshold (TPM value between 10-100 - moderately expressed; TPM value<10 is lowly expressed and TPM value >100 is highly expressed)
#Human Protein Atlas Citation is required
#random.random() uses mersene twister. # developed by Makoto Matsumoto and Takuji Nishimura
#!pip install tkinter
#stage in gynaecological cancers follow FIGO (International Federation of Gynecology and Obstetrics) staging system
#Stage 1 tumor confined to uterus
#1A <50 percent myometrial invasion and confined to uterus
#IB >50 percent invasion and confined to uterus
#STAGEII spread to Cervical stroma
#StageIIIA (spread to adnex(ovaries / fallopian tubes) and serosa(adjacent structures(paracancer)-perimetrium))
#IIIB	Vaginal/parametrial involvement
#IIIC1	Pelvic lymph nodes involved
#IIIC2	Para-aortic lymph nodes involved(abdominal aorta)
#IVA	Bladder/bowel mucosa invaded
#IVB	Distant metastasis
#stage is anatomical
#Myometrium thickness is around 2-40 mm
#Myometrial invasion cannot exceed this. 5mm is considered normal
#Nulliparity means has the women ever been pregnant
#Tumor _ type refers to where the cancer originates , thor organ or tissue
#Grade describes how abnormal the cancer cells are, which gives an indication, how likely the cell is to grow .The more the cancer cells look like normal cells, the lower the grade. The more abnormal they look,
#the higher the grade
#Degree of Differenctiation: This refers to how much the cancer cells resemble normal cells in the tissue.High grade tumors are poorly differentiated.
#Endometrioid carcinoma(Tumor type) (the most common form).(70-80 percent cases)

#Serous carcinoma, clear cell carcinoma, and other rarer types.


# Copyright (c) 2026 Neha Arora
# Licensed under the MIT License.

"""
Log2 fold change range:

log2FC of -3 to 3: This range will cover a broad spectrum of upregulation and downregulation, from small changes to more extreme alterations.

log2FC of -1 to 2: A more moderate range often seen in gene expression changes that are biologically relevant.

log2FC of -0.5 to 1: For simulating small or subtle changes in protein abundance."""

!pip install gradio --quiet
#packages to import
import ast
from collections import Counter
import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random

!pip freeze > requirements.txt

#Data compiled from Literature
#Global variables, lists and dictionaries

protein_abundance_dictionary = {"Gene": ['IFIT3','PARP9','SLC34A2',  'CYB5R1','PTPN1','DPT','SLP','ANXA2','PRDX1','CTNNB','HMGB3','CLC1','EIF4A1','PRDX6','ENO1','ANXA4','EMD','KU70','GRP78','GSTP1','ACTG','DIA3','ENOA','ALBU',
'ACTB','ACTG','KRT8','ANXA1','ENOA','TRFE','HSPB1','EF-TU','IDH1','SOD1','CALR','RPSA','UAP56','PSME1','PDIA3','CAH1','IDHC','PPIA','PPIB','ZNF844','ALDOA','ENO1','KRT10','ABRACL','PGAM2',
'FGB','ANXA3','CTNB1','XPO2','CAPG','MMP9','EWSR1','PKM','NAMPT','ENOA','CATD','LDHA','SPIT1','OSTP','MPO','CASP3','CADH1','TUBA1A','TIGAR','SEC11A','CENPV','TMSB4X','COL1A2','S100A16','NEBL','OGN','COL1A2','S100A16','SLC9A3R1','DNAJB11','RBBP4','MYH11','OGN','GNLY',
'MZB1','MX1','NANS','TMED9','TPPP3','HNRNPF','NOLC1','SLC4A1','COL5A1','FGA','HBA1','COL1A2','SNRPC','UBE2V2','COL1A1','BCAM','PTMA','DEFA1','S100A8','LTF','CAMP','AZU1','COL1A2','SEC63','LDHB','ABHD14B','LTF','SARS1','ATP1B1','IARS1','PNP','SFN','ACTA2','TPR','MAP4','HBG2','PSMD11','SLC2A11','SLC2A1','SRRM2','U2AF1','TMSB4X','DVL-2','HSP8','EIF4G2','F13A1','GFM1','NPEPL1','SARS2',
'SNTB1','UBR4','USP47','WDR5','ASS1','PFAS','ckb','hk2','MAPKAPK3','SERPINA1','TAGLN2','TPI1','ENO1','ANXA2','ANXA1','SRPK1','PTPN6','ATP5A',
  'TUBB','ERBB2','EGFR','ACTN4','UBE2N','PKM2','HSPA5','LMNAA/C','HRNR','MDH2','STMN1','CKB','DJ-1','PRKCSH','NCL','GON7','APOA1',
'S100A','PKM2','HSP10','EC1','EC2','PKM1','WFDC2','CLU','MUC5B','COX2','PRDX3','PRDX5','PRDX6','RDX4','HNRNPA1','CTSB','CALU','CACYBP',
'LDHA','P38MAPK','NFKB','ERK1/2','PRDX6','EIF4A1','CLIC1','CLIC4','TAGLN2','TPI1','TPI-1','HSPA8','ATF2','JUN','TAF1','HNF4A','ATF7IP','ERBB2','EGFR',
'JPT1','CALR','RPSA','ACTB','IDH1','MLH1','EPM2AIP1','SRPK1','CAPS','PRTN3','HMGA2','S100A8','LTF','CTSD','STMN1','TAGLN','DES','CALD1','CNN1','CDH13',
  'PARP9','IFIT3','DPT','SLP1','OXSR1','ASS1'],"Regulation": ['UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'UP',	'UP',	'UP',	'DOWN',	'UP',	'DOWN',	'UP',	'UP',	'UP',
  'DOWN',	'UP/DOWN',	'UP/DOWN',	'UP',	'UP',	'UP',	'DOWN',	'UP/DOWN',	'UP',	'DOWN',	'DOWN',	'UP',	'UP',	'UP',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',
  'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP',	'UP',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP',	'UP',	'UP',	'UP',	'DOWN',
  'DOWN',	'DOWN',	'DOWN',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'DOWN',
  'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'DOWN',	'DOWN',	'UP',	'UP/DOWN',
  'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',
  'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP/DOWN',	'UP',	'UP/Down',	'UP/Down',	'UP/Down',	'UP/Down',	'UP/DOWN',	'UP/Down',
  'UP/Down',	'UP/Down',	'UP/Down',	'UP',	'UP',	'UP',	'UP',	'UP',	'LOW',	'LOW',	'LOW',	'LOW',	'UP',	'UP',	'UP',	'UP',	'UP',	'LOW',	'LOW',
  'UP/DOWN',	'UP/DOWN',	'UP',	'UP',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',
  'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',
  'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'DOWN',	'DOWN',	'UP',	'UP',	'DOWN',	'DOWN',	'DOWN',	'DOWN'], "Factor":[
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'STAGE1A',	'STAGE2,stage3',	'NA',	'STAGE2',
'NA',	'NA',	'STAGE1B,stage3',	'NA',	'STAGE3',	'NA',	'STAGE3',	'STAGE3',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'POSTMENOPAUSAL',
'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'POSTMENOPAUSAL',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'GRADE2',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'NA',
'NA',	'NA',	'NA',	'NA',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'Grade3',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'TYPE 2',	'TYPE 1',	'NA',	'NA',	'NA',	'NA',
'GRADE1,grade3,stage1,stage3',	'GRADE1,GRADE3',	'NA',	'TYPE1',	'TYPE1',	'TYPE1',	'STAGE1A,STAGE1B',	'NA',	'NA',	'NA',	'NA',	'type 1',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'stage1B',	'NA',	'NA',	'NA',	'stage1A',	'NA',	'NA',	'NA',	'NA',	'NA',
'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA',	'NA']}

print(len(protein_abundance_dictionary["Gene"]))
#global variables
clinical_data=[]
protein_data=[]
normal_tissue_expression=pd.read_csv('/content/NOT_new_rna.tsv',sep='\t')
number_of_proteins=normal_tissue_expression.shape[0]
protein=normal_tissue_expression['Gene'].values
normal_tissue_prognostic=normal_tissue_expression['Cancer prognostics - Uterine Corpus Endometrial Carcinoma (TCGA)'].astype(str).apply(lambda x: x.strip("unprognostic ()"))
normal_tissue_prognostic=pd.to_numeric(normal_tissue_prognostic,errors="coerce")
normal_tissue_prognostic=normal_tissue_prognostic.astype(float)
normal_tisue_regulation=normal_tissue_expression['Tissue RNA - endometrium 1 [nTPM]'].apply(lambda x: "up" if x>100 else "down" if x>=10 and x<=100 else "moderate")
gene_prognosis_indicator=normal_tissue_prognostic.apply(lambda x: "yes" if x<=0.05 else "no")
regulation=[]
generate_abundance={}
index_protein=""
index_normal=""

#Generation of the clinical Data(Synthetic Data)

def generate_person_data(num_records,selected_columns):

  #Generation of Clinical Data
      global clinical_data
      patient_id=[]
      Treatment=[]
      Menopause=[]
      Grade=[]
      Stage=[]
      Myometrial_invasion=[]
      Nulliparity=[]
      Tumor_type=[]
      for i in range(num_records):
         patient_id.append(f"E{i}")
         Treatment.append(random.choice(["yes","no"]))
         Myometrial_invasion.append(round(random.uniform(5, 40), 2))

      mean_age = 60
      std_dev = 15
      np.random.seed(42)
      mean_bmi = 25      # Mean BMI (typical value)
      sigma_bmi = 4    # Standard deviation (variation in BMI)     # Number of samples to generate

      # Generate random BMI values following a normal distribution
      bmi_values = np.random.normal(mean_bmi, sigma_bmi, num_records)
      bmi_values=np.clip(bmi_values,21,40)
      bmi_values = np.round(bmi_values, 2)
      Ages = np.random.normal(mean_age, std_dev, size=num_records).astype(int)   #1
      Ages=np.clip(Ages,30,85)

      for i in Ages:
          if i<=51:
             Menopause.append(1)      #2 pre-menopause
          else:
             Menopause.append(2)      # post-menopausal

      for i in Ages:
           if i<=35:
             Nulliparity.extend(random.choices(["yes","no"],[0.5,0.5],k=1))
           else:
             Nulliparity.extend(random.choices(["yes","no"],[0.6,0.4],k=1))
      for index,i in enumerate(Ages):
          if i>=60 and Nulliparity[index]=='yes'and bmi_values[index]>=25:
             Tumor_type.extend(random.choices(['Type1','Type2'],[0.4,0.6],k=1))
             if Tumor_type[index]=='Type1':
                Grade.extend(random.choices(['Grade1','Grade2','Grade3'],[0.5,0.3,0.2],k=1))
                if Grade[index]=='Type1' or Grade[index]=='Type2':
                  weights = [0.1333] * 6 + [0.05] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))
                else:
                  weights = [0.05] * 6 + [0.1333] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))

             else:
                Grade.extend(random.choices(['Grade1','Grade2','Grade3'],[0.2,0.3,0.5],k=1))
                if Grade[index]=='Grade1' or Grade[index]=='Grade2':
                  weights = [0.1333] * 6 + [0.05] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))
                else:
                  weights = [0.05] * 6 + [0.1333] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))
          else:
            Tumor_type.extend(random.choices(['Type1','Type2'],[0.8,0.2],k=1))
            if Tumor_type[index]=='Type1':
                Grade.extend(random.choices(['Grade1','Grade2','Grade3'],[0.5,0.3,0.2],k=1))
                if Grade[index]=='Grade1' or Grade[index]=='Grade2':
                  weights = [0.1333] * 6 + [0.05] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))
                else:
                  weights = [0.05] * 6 + [0.1333] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))

            else:
                Grade.extend(random.choices(['Grade1','Grade2','Grade3'],[0.2,0.3,0.5],k=1))
                if Grade[index]=='Grade1' or Grade[index]=='Grade2':
                  weights = [0.1333] * 6 + [0.05] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))
                else:
                  weights = [0.05] * 6 + [0.1333] * 4
                  Stage.extend(random.choices(['Stage1','Stage1A','Stage1B','Stage2','Stage2A','Stage2B','Stage3C1','Stage3C2','Stage4A','Stage4B'], weights=weights,k=1))



      clinical_data=pd.DataFrame({'Patient_ID': patient_id,'Ages':Ages,'Menopause':Menopause,'Grade':Grade,'Tumor_type':Tumor_type,'Stage': Stage,'Nulliparity':Nulliparity,'BMI':bmi_values,'Myometrial':Myometrial_invasion,'Treatment':Treatment})
      clinical_data.to_csv('clinical_data.csv')

      return clinical_data[selected_columns]



def generate_protein_abundance_data(num_records,protein_list):
  all_outputs=[]
  for j in range(num_records):
   for i in protein_list:
      try:
       index_protein=protein_abundance_dictionary['Gene'].index(i.lower())

      except ValueError:
        index_protein=None
      try:
        index_normal=normal_tissue_expression['Gene'].str.lower().tolist().index(i.lower())
      except ValueError:
        index_normal=None
      if index_protein is not None and index_normal is not None and  protein_abundance_dictionary['Factor'][index_protein] == "NA":
         print("checkpointer1")
         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" :
           generate_abundance[i]=np.random.normal(loc=2, scale=0.4)
           generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" :
          #difference=abundance[index]-0.5
           generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
           generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="down" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" :
           generate_abundance[i]=np.random.normal(loc=2, scale=0.4)
           generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="down" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" :
           generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
           generate_abundance[i] = np.clip(generate_abundance[i],0,3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="yes" :
           if normal_tisue_regulation[index_normal]=="up":
              generate_abundance[i] = np.random.normal(loc=2, scale=0.4)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
           elif normal_tisue_regulation[index_normal]=="down":
              generate_abundance[i] = np.random.normal(loc=-2, scale=0.4)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],-3, 0)
           else:
              generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
              generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="no" :
           if normal_tisue_regulation[index_normal]=="up":
              generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
           elif normal_tisue_regulation[index_normal]=="down":
              generate_abundance[i] = np.random.normal(loc=-1, scale=0.3)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],-3, 0)
           else:
              generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
              generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" :
           generate_abundance[i] = np.random.normal(loc=-2, scale=0.4) # mean around -1.5
           generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" :
          #difference=abundance[index]-0.5
           generate_abundance[i] = np.random.normal(loc=-1, scale=0.3) # mean around -1.5
           generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="down" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" :
           generate_abundance[i] = np.random.normal(loc=-2, scale=0.4) # mean around -1.5
           generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="down" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" :
           generate_abundance[i] = np.random.normal(loc=-1, scale=0.3) # mean around -1.5
           generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
      elif index_protein is None and index_normal is not None:
         print("checkpointer2")
         if normal_tisue_regulation[index_normal]=="up" and gene_prognosis_indicator[index_normal]=="yes" :
            generate_abundance[i] = np.random.normal(loc=2, scale=0.4)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
         elif normal_tisue_regulation[index_normal]=="up" and  gene_prognosis_indicator[index_normal]=="no" :
            generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
         elif normal_tisue_regulation[index_normal]=="down" and gene_prognosis_indicator[index_normal]=="yes" :
            generate_abundance[i] = np.random.normal(loc=-2, scale=0.4) # mean around -1.5
            generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
         elif normal_tisue_regulation[index_normal]=="down" and gene_prognosis_indicator[index_normal]=="no" :
            generate_abundance[i] = np.random.normal(loc=-1, scale=0.3)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],-3,0)
         else:
            generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

      elif index_protein is not None and index_normal is None and protein_abundance_dictionary['Factor'][index_protein] == "NA":
         print("checkpointer3")
         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and gene_prognosis_indicator[index_normal]=="yes" :
            generate_abundance[i] = np.random.normal(loc=2, scale=0.4)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and  gene_prognosis_indicator[index_normal]=="no" :
            generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and gene_prognosis_indicator[index_normal]=="yes" :
            generate_abundance[i] = np.random.normal(loc=-2, scale=0.4) # mean around -1.5
            generate_abundance[i] = np.clip(generate_abundance[i], -3, 0)
         elif protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and gene_prognosis_indicator[index_normal]=="no" :
            generate_abundance[i] = np.random.normal(loc=-1, scale=0.3)  # mean 0
            generate_abundance[i] = np.clip(generate_abundance[i],-3,0)
         else:
            generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

      elif index_protein is not None and index_normal is None and protein_abundance_dictionary['Factor'][index_protein] != "NA":
         print("checkpointer4")
         list1=clinical_data['Stage'].unique()
         list2=clinical_data['Grade'].unique()
         list3=clinical_data['Menopause'].unique()
         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=2, scale=0.4)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up"  and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=1, scale=0.3)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=-2, scale=0.4)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=-1, scale=0.3)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
            generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)


         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
            generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

      elif index_protein is None and index_normal is None:
         print("checkpointer5")
         generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
         generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)


      elif index_protein is not None and index_normal is not None and protein_abundance_dictionary['Factor'][index_protein] != "NA":
         print("checkpointer6")
         list1=clinical_data['Stage'].unique()
         list2=clinical_data['Grade'].unique()
         list3=clinical_data['Menopause'].unique()
         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=2, scale=0.4)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=1, scale=0.3)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=-2, scale=0.4)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="down" and (normal_tisue_regulation[index_normal]=="up" or normal_tisue_regulation[index_normal]=="moderate") and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
          generate_abundance[i]=np.random.normal(loc=-1, scale=0.3)
          generate_abundance[i] = np.clip(generate_abundance[i], 0, 3)
         else:
          generate_abundance[i]=np.random.normal(loc=0.0, scale=0.5)
          generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)

         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="yes" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
           if normal_tisue_regulation[index_normal]=="up":
              generate_abundance[i] = np.random.normal(loc=2, scale=0.4)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
           elif normal_tisue_regulation[index_normal]=="down":
              generate_abundance[i] = np.random.normal(loc=-2, scale=0.4)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],-3, 0)
           else:
            generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)


         if protein_abundance_dictionary['Regulation'][index_protein].lower()=="up/down" and gene_prognosis_indicator[index_normal]=="no" and protein_abundance_dictionary['Factor'][index_protein].splt('/',',').lower() in (list1 + list2 +list3):
           if normal_tisue_regulation[index_normal]=="up":
              generate_abundance[i] = np.random.normal(loc=1, scale=0.3)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],0, 3)
           elif normal_tisue_regulation[index_normal]=="down":
              generate_abundance[i] = np.random.normal(loc=-1, scale=0.3)  # mean 0
              generate_abundance[i] = np.clip(generate_abundance[i],-3, 0)

           else:
            generate_abundance[i] = np.random.normal(loc=0.0, scale=0.5)
            generate_abundance[i] = np.clip(generate_abundance[i], -1.5, 1.5)
   #out = generate_abundance        # your JSON dictionary
   all_outputs.append((f"Patient{j}",generate_abundance.copy()))
  return all_outputs

def wrapper(num_records,text_input):
   try:
     lst=ast.literal_eval(text_input)
     if isinstance(lst, str):
        lst = [lst]     # wrap string as list

        # If tuple → convert to list
     if isinstance(lst, tuple):
        lst = list(lst)

        # Ensure output is a list
     if not isinstance(lst, list):
        lst = [lst]

   except:
     lst=[x.strip() for x in text_input.split(",") if x.strip()]
   print(lst)
   return generate_protein_abundance_data(num_records,protein_list=lst)




def plots():
   fig, axes=plt.subplots(5,2,figsize=(20,10),squeeze=False)
   plt.suptitle("Plots")
   c,index=(0,0)
   for i in clinical_data.columns:
      axes[c,index].hist(i,bins=3,orientation='vertical',data=clinical_data)
      axes[c,index].set_title(i)
      index+=1
      if index==2:
         index=0
         c+=1
   plt.tight_layout()
   return plt

from  fastapi import FastAPI
from gradio.routes import mount_gradio_app
with gr.Blocks() as demo:
    with gr.Tab("Clinical Data"):
        gr.Interface(fn=generate_person_data, inputs=[gr.Number(),gr.CheckboxGroup(
            choices=["Patient_ID", "Ages", "Menopause","Grade","Tumor_type","Stage","Nulliparity","BMI","Myometrial","Treatment"],
            label="Select Columns"
        )], outputs="dataframe")


    with gr.Tab("Protein Data"):
        num_records = gr.Number(label="num_records")
        protein_list = gr.Textbox(lines=5, label="Protein List")
        btn = gr.Button("Generate")
        out = gr.JSON(label="Abundance Output")
        btn.click(wrapper, inputs=[num_records, protein_list], outputs=out)
        #gr.Interface(fn=wrapper, inputs=[gr.Number(),gr.Textbox(lines=5,placeholder="Enter a list",label="Protein List")], outputs="dataframe", title="Proteomics Data Generator")
    with gr.Tab("Plots"):
        btn = gr.Button("Generate")
        out = gr.Plot()
        btn.click(plots, inputs=[], outputs=out)


        #gr.Interface(fn=plots, inputs=[], outputs="plot", title="Plots")
demo.launch()